/// An opaque notebook identity owned and generated by the repository.
///
/// Durable storage is out of scope for this iteration (spec Non-Goals); the id
/// only has to be stable and unique within a session.
class Notebook {
  final String id;
  final String title;
  final DateTime createdAt;

  const Notebook({
    required this.id,
    required this.title,
    required this.createdAt,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Notebook &&
          other.id == id &&
          other.title == title &&
          other.createdAt == createdAt;

  @override
  int get hashCode => Object.hash(id, title, createdAt);

  @override
  String toString() => 'Notebook($id, $title)';
}