// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/objectbox/ob_chunk.dart';
import 'data/objectbox/ob_device_meta.dart';
import 'data/objectbox/ob_document.dart';
import 'data/objectbox/ob_notebook.dart';
import 'data/objectbox/ob_peer_watermark.dart';
import 'data/objectbox/ob_publication.dart';
import 'data/objectbox/ob_tombstone.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 704321496293028603),
    name: 'ObChunk',
    lastPropertyId: const obx_int.IdUid(8, 7066455285199650782),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4205478080294508066),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2545353443264043245),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4632753525854541785),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3687768499452632643),
        name: 'tokenCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2585631046161634708),
        name: 'publicationId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 3878306667357017887),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5431290853376932398),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 3658022468459967422),
        hnswParams: obx_int.ModelHnswParams(
          dimensions: 256,
          neighborsPerNode: 16,
          indexingSearchCount: 100,
          distanceType: 2,
        ),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6765881571618015498),
        name: 'publicationRef',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 7270646584030581096),
        relationField: 'publication',
        relationTarget: 'ObPublication',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7066455285199650782),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 815090204877900177),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7052576167656126206),
    name: 'ObNotebook',
    lastPropertyId: const obx_int.IdUid(5, 8145360642477349462),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2162858547817253679),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 664191283401452871),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 1268075715827330327),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7394419024957424482),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1796745296811812000),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8145360642477349462),
        name: 'versionCounter',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(18, 6407404442283004917),
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 1995037125426230318),
        name: 'publications',
        targetId: const obx_int.IdUid(3, 741772455080352949),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 741772455080352949),
    name: 'ObPublication',
    lastPropertyId: const obx_int.IdUid(11, 6597143761411765895),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6934585096269154726),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8683706986566750584),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 1001549938926233033),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7916978488692258549),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4441387091471985922),
        name: 'byteSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 368365639131557741),
        name: 'importedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6988823470578868541),
        name: 'embeddingModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3684581771981739796),
        name: 'chunkCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4939352351361956814),
        name: 'documentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 4214575186326701269),
        relationField: 'document',
        relationTarget: 'ObDocument',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9021370137210801339),
        name: 'chunkSetVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6597143761411765895),
        name: 'versionCounter',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(13, 4397252534325219387),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'notebooks',
        srcEntity: 'ObNotebook',
        srcField: 'publications',
      ),
      obx_int.ModelBacklink(
        name: 'chunks',
        srcEntity: 'ObChunk',
        srcField: 'publication',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7735928096252811792),
    name: 'ObDocument',
    lastPropertyId: const obx_int.IdUid(6, 352596525888535513),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1029677992573457998),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5522082270764807201),
        name: 'publicationId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 6381488535176747878),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4167258760522526470),
        name: 'markdown',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 275914293046299287),
        name: 'documentOwnerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 4971187274316308831),
        relationField: 'publication',
        relationTarget: 'ObPublication',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5710842496020228193),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(10, 1174962132004444624),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 352596525888535513),
        name: 'versionCounter',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(12, 4747252638121359531),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2392655260168779415),
    name: 'ObTombstone',
    lastPropertyId: const obx_int.IdUid(4, 464553973947380079),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3277224290654947897),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1547092632712737381),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 1942234577867014399),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3827636529209907398),
        name: 'deletedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 464553973947380079),
        name: 'versionCounter',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(15, 3661008356289407718),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5927871254448174977),
    name: 'ObDeviceMeta',
    lastPropertyId: const obx_int.IdUid(2, 3376840629114837181),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2459595963616113932),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3376840629114837181),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 4947092806904792774),
    name: 'ObPeerWatermark',
    lastPropertyId: const obx_int.IdUid(9, 6557759549076685612),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1856504160593732827),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6095469060555583671),
        name: 'peerDeviceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 3401610433590760090),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 712243762917571978),
        name: 'recordUuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(16, 3574921918337753410),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5619551039152638082),
        name: 'metadataCounter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6750946875517745893),
        name: 'chunkSetCounter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2940185484612297280),
        name: 'documentCounter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6557759549076685612),
        name: 'recordKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(17, 8583363602344405022),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 4947092806904792774),
    lastIndexId: const obx_int.IdUid(18, 6407404442283004917),
    lastRelationId: const obx_int.IdUid(2, 2721689940511666391),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4257374981615794318,
      6851845237337135813,
      6103110862433255594,
    ],
    retiredRelationUids: const [2721689940511666391],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ObChunk: obx_int.EntityDefinition<ObChunk>(
      model: _entities[0],
      toOneRelations: (ObChunk object) => [object.publication],
      toManyRelations: (ObChunk object) => {},
      getId: (ObChunk object) => object.id,
      setId: (ObChunk object, int id) {
        object.id = id;
      },
      objectToFB: (ObChunk object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        final uuidOffset = fbb.writeString(object.uuid);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.chunkIndex);
        fbb.addOffset(2, contentOffset);
        fbb.addInt64(3, object.tokenCount);
        fbb.addInt64(4, object.publicationId);
        fbb.addOffset(5, embeddingOffset);
        fbb.addInt64(6, object.publication.targetId);
        fbb.addOffset(7, uuidOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final chunkIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final tokenCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final publicationIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final object = ObChunk(
          uuid: uuidParam,
          chunkIndex: chunkIndexParam,
          content: contentParam,
          tokenCount: tokenCountParam,
          publicationId: publicationIdParam,
          embedding: embeddingParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.publication.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.publication.attach(store);
        return object;
      },
    ),
    ObNotebook: obx_int.EntityDefinition<ObNotebook>(
      model: _entities[1],
      toOneRelations: (ObNotebook object) => [],
      toManyRelations: (ObNotebook object) => {
        obx_int.RelInfo<ObNotebook>.toMany(1, object.id): object.publications,
      },
      getId: (ObNotebook object) => object.id,
      setId: (ObNotebook object, int id) {
        object.id = id;
      },
      objectToFB: (ObNotebook object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.versionCounter);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          isUtc: true,
        );
        final versionCounterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = ObNotebook(
          uuid: uuidParam,
          title: titleParam,
          createdAt: createdAtParam,
          versionCounter: versionCounterParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<ObNotebook>(
          object.publications,
          store,
          obx_int.RelInfo<ObNotebook>.toMany(1, object.id),
        );
        return object;
      },
    ),
    ObPublication: obx_int.EntityDefinition<ObPublication>(
      model: _entities[2],
      toOneRelations: (ObPublication object) => [object.document],
      toManyRelations: (ObPublication object) => {
        obx_int.RelInfo<ObNotebook>.toManyBacklink(1, object.id):
            object.notebooks,
        obx_int.RelInfo<ObChunk>.toOneBacklink(
          7,
          object.id,
          (ObChunk srcObject) => srcObject.publication,
        ): object.chunks,
      },
      getId: (ObPublication object) => object.id,
      setId: (ObPublication object, int id) {
        object.id = id;
      },
      objectToFB: (ObPublication object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final embeddingModelIdOffset = fbb.writeString(object.embeddingModelId);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(4, object.byteSize);
        fbb.addInt64(5, object.importedAt.millisecondsSinceEpoch);
        fbb.addOffset(6, embeddingModelIdOffset);
        fbb.addInt64(7, object.chunkCount);
        fbb.addInt64(8, object.document.targetId);
        fbb.addInt64(9, object.chunkSetVersion);
        fbb.addInt64(10, object.versionCounter);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final byteSizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final importedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          isUtc: true,
        );
        final embeddingModelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final chunkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final chunkSetVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final versionCounterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = ObPublication(
          uuid: uuidParam,
          title: titleParam,
          byteSize: byteSizeParam,
          importedAt: importedAtParam,
          embeddingModelId: embeddingModelIdParam,
          chunkCount: chunkCountParam,
          chunkSetVersion: chunkSetVersionParam,
          versionCounter: versionCounterParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.document.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.document.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ObPublication>(
          object.notebooks,
          store,
          obx_int.RelInfo<ObNotebook>.toManyBacklink(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<ObPublication>(
          object.chunks,
          store,
          obx_int.RelInfo<ObChunk>.toOneBacklink(
            7,
            object.id,
            (ObChunk srcObject) => srcObject.publication,
          ),
        );
        return object;
      },
    ),
    ObDocument: obx_int.EntityDefinition<ObDocument>(
      model: _entities[3],
      toOneRelations: (ObDocument object) => [object.publication],
      toManyRelations: (ObDocument object) => {},
      getId: (ObDocument object) => object.id,
      setId: (ObDocument object, int id) {
        object.id = id;
      },
      objectToFB: (ObDocument object, fb.Builder fbb) {
        final markdownOffset = fbb.writeString(object.markdown);
        final uuidOffset = fbb.writeString(object.uuid);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.publicationId);
        fbb.addOffset(2, markdownOffset);
        fbb.addInt64(3, object.publication.targetId);
        fbb.addOffset(4, uuidOffset);
        fbb.addInt64(5, object.versionCounter);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final publicationIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final markdownParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final versionCounterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = ObDocument(
          uuid: uuidParam,
          publicationId: publicationIdParam,
          markdown: markdownParam,
          versionCounter: versionCounterParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.publication.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.publication.attach(store);
        return object;
      },
    ),
    ObTombstone: obx_int.EntityDefinition<ObTombstone>(
      model: _entities[4],
      toOneRelations: (ObTombstone object) => [],
      toManyRelations: (ObTombstone object) => {},
      getId: (ObTombstone object) => object.id,
      setId: (ObTombstone object, int id) {
        object.id = id;
      },
      objectToFB: (ObTombstone object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.deletedAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.versionCounter);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final deletedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          isUtc: true,
        );
        final versionCounterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = ObTombstone(
          uuid: uuidParam,
          deletedAt: deletedAtParam,
          versionCounter: versionCounterParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ObDeviceMeta: obx_int.EntityDefinition<ObDeviceMeta>(
      model: _entities[5],
      toOneRelations: (ObDeviceMeta object) => [],
      toManyRelations: (ObDeviceMeta object) => {},
      getId: (ObDeviceMeta object) => object.id,
      setId: (ObDeviceMeta object, int id) {
        object.id = id;
      },
      objectToFB: (ObDeviceMeta object, fb.Builder fbb) {
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = ObDeviceMeta(id: idParam, value: valueParam);

        return object;
      },
    ),
    ObPeerWatermark: obx_int.EntityDefinition<ObPeerWatermark>(
      model: _entities[6],
      toOneRelations: (ObPeerWatermark object) => [],
      toManyRelations: (ObPeerWatermark object) => {},
      getId: (ObPeerWatermark object) => object.id,
      setId: (ObPeerWatermark object, int id) {
        object.id = id;
      },
      objectToFB: (ObPeerWatermark object, fb.Builder fbb) {
        final peerDeviceIdOffset = fbb.writeString(object.peerDeviceId);
        final recordUuidOffset = fbb.writeString(object.recordUuid);
        final recordKeyOffset = fbb.writeString(object.recordKey);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, peerDeviceIdOffset);
        fbb.addOffset(4, recordUuidOffset);
        fbb.addInt64(5, object.metadataCounter);
        fbb.addInt64(6, object.chunkSetCounter);
        fbb.addInt64(7, object.documentCounter);
        fbb.addOffset(8, recordKeyOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final peerDeviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final recordUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final metadataCounterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final chunkSetCounterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final documentCounterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object =
            ObPeerWatermark(
                peerDeviceId: peerDeviceIdParam,
                recordUuid: recordUuidParam,
                metadataCounter: metadataCounterParam,
                chunkSetCounter: chunkSetCounterParam,
                documentCounter: documentCounterParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..recordKey = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 20, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ObChunk] entity fields to define ObjectBox queries.
class ObChunk_ {
  /// See [ObChunk.id].
  static final id = obx.QueryIntegerProperty<ObChunk>(
    _entities[0].properties[0],
  );

  /// See [ObChunk.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<ObChunk>(
    _entities[0].properties[1],
  );

  /// See [ObChunk.content].
  static final content = obx.QueryStringProperty<ObChunk>(
    _entities[0].properties[2],
  );

  /// See [ObChunk.tokenCount].
  static final tokenCount = obx.QueryIntegerProperty<ObChunk>(
    _entities[0].properties[3],
  );

  /// See [ObChunk.publicationId].
  static final publicationId = obx.QueryIntegerProperty<ObChunk>(
    _entities[0].properties[4],
  );

  /// See [ObChunk.embedding].
  static final embedding = obx.QueryHnswProperty<ObChunk>(
    _entities[0].properties[5],
  );

  /// See [ObChunk.publication].
  static final publication = obx.QueryRelationToOne<ObChunk, ObPublication>(
    _entities[0].properties[6],
  );

  /// See [ObChunk.uuid].
  static final uuid = obx.QueryStringProperty<ObChunk>(
    _entities[0].properties[7],
  );
}

/// [ObNotebook] entity fields to define ObjectBox queries.
class ObNotebook_ {
  /// See [ObNotebook.id].
  static final id = obx.QueryIntegerProperty<ObNotebook>(
    _entities[1].properties[0],
  );

  /// See [ObNotebook.uuid].
  static final uuid = obx.QueryStringProperty<ObNotebook>(
    _entities[1].properties[1],
  );

  /// See [ObNotebook.title].
  static final title = obx.QueryStringProperty<ObNotebook>(
    _entities[1].properties[2],
  );

  /// See [ObNotebook.createdAt].
  static final createdAt = obx.QueryDateProperty<ObNotebook>(
    _entities[1].properties[3],
  );

  /// See [ObNotebook.versionCounter].
  static final versionCounter = obx.QueryIntegerProperty<ObNotebook>(
    _entities[1].properties[4],
  );

  /// see [ObNotebook.publications]
  static final publications =
      obx.QueryRelationToMany<ObNotebook, ObPublication>(
        _entities[1].relations[0],
      );
}

/// [ObPublication] entity fields to define ObjectBox queries.
class ObPublication_ {
  /// See [ObPublication.id].
  static final id = obx.QueryIntegerProperty<ObPublication>(
    _entities[2].properties[0],
  );

  /// See [ObPublication.uuid].
  static final uuid = obx.QueryStringProperty<ObPublication>(
    _entities[2].properties[1],
  );

  /// See [ObPublication.title].
  static final title = obx.QueryStringProperty<ObPublication>(
    _entities[2].properties[2],
  );

  /// See [ObPublication.byteSize].
  static final byteSize = obx.QueryIntegerProperty<ObPublication>(
    _entities[2].properties[3],
  );

  /// See [ObPublication.importedAt].
  static final importedAt = obx.QueryDateProperty<ObPublication>(
    _entities[2].properties[4],
  );

  /// See [ObPublication.embeddingModelId].
  static final embeddingModelId = obx.QueryStringProperty<ObPublication>(
    _entities[2].properties[5],
  );

  /// See [ObPublication.chunkCount].
  static final chunkCount = obx.QueryIntegerProperty<ObPublication>(
    _entities[2].properties[6],
  );

  /// See [ObPublication.document].
  static final document = obx.QueryRelationToOne<ObPublication, ObDocument>(
    _entities[2].properties[7],
  );

  /// See [ObPublication.chunkSetVersion].
  static final chunkSetVersion = obx.QueryIntegerProperty<ObPublication>(
    _entities[2].properties[8],
  );

  /// See [ObPublication.versionCounter].
  static final versionCounter = obx.QueryIntegerProperty<ObPublication>(
    _entities[2].properties[9],
  );

  /// see [ObPublication.chunks]
  static final chunks = obx.QueryBacklinkToMany<ObChunk, ObPublication>(
    ObChunk_.publication,
  );
}

/// [ObDocument] entity fields to define ObjectBox queries.
class ObDocument_ {
  /// See [ObDocument.id].
  static final id = obx.QueryIntegerProperty<ObDocument>(
    _entities[3].properties[0],
  );

  /// See [ObDocument.publicationId].
  static final publicationId = obx.QueryIntegerProperty<ObDocument>(
    _entities[3].properties[1],
  );

  /// See [ObDocument.markdown].
  static final markdown = obx.QueryStringProperty<ObDocument>(
    _entities[3].properties[2],
  );

  /// See [ObDocument.publication].
  static final publication = obx.QueryRelationToOne<ObDocument, ObPublication>(
    _entities[3].properties[3],
  );

  /// See [ObDocument.uuid].
  static final uuid = obx.QueryStringProperty<ObDocument>(
    _entities[3].properties[4],
  );

  /// See [ObDocument.versionCounter].
  static final versionCounter = obx.QueryIntegerProperty<ObDocument>(
    _entities[3].properties[5],
  );
}

/// [ObTombstone] entity fields to define ObjectBox queries.
class ObTombstone_ {
  /// See [ObTombstone.id].
  static final id = obx.QueryIntegerProperty<ObTombstone>(
    _entities[4].properties[0],
  );

  /// See [ObTombstone.uuid].
  static final uuid = obx.QueryStringProperty<ObTombstone>(
    _entities[4].properties[1],
  );

  /// See [ObTombstone.deletedAt].
  static final deletedAt = obx.QueryDateProperty<ObTombstone>(
    _entities[4].properties[2],
  );

  /// See [ObTombstone.versionCounter].
  static final versionCounter = obx.QueryIntegerProperty<ObTombstone>(
    _entities[4].properties[3],
  );
}

/// [ObDeviceMeta] entity fields to define ObjectBox queries.
class ObDeviceMeta_ {
  /// See [ObDeviceMeta.id].
  static final id = obx.QueryIntegerProperty<ObDeviceMeta>(
    _entities[5].properties[0],
  );

  /// See [ObDeviceMeta.value].
  static final value = obx.QueryStringProperty<ObDeviceMeta>(
    _entities[5].properties[1],
  );
}

/// [ObPeerWatermark] entity fields to define ObjectBox queries.
class ObPeerWatermark_ {
  /// See [ObPeerWatermark.id].
  static final id = obx.QueryIntegerProperty<ObPeerWatermark>(
    _entities[6].properties[0],
  );

  /// See [ObPeerWatermark.peerDeviceId].
  static final peerDeviceId = obx.QueryStringProperty<ObPeerWatermark>(
    _entities[6].properties[1],
  );

  /// See [ObPeerWatermark.recordUuid].
  static final recordUuid = obx.QueryStringProperty<ObPeerWatermark>(
    _entities[6].properties[2],
  );

  /// See [ObPeerWatermark.metadataCounter].
  static final metadataCounter = obx.QueryIntegerProperty<ObPeerWatermark>(
    _entities[6].properties[3],
  );

  /// See [ObPeerWatermark.chunkSetCounter].
  static final chunkSetCounter = obx.QueryIntegerProperty<ObPeerWatermark>(
    _entities[6].properties[4],
  );

  /// See [ObPeerWatermark.documentCounter].
  static final documentCounter = obx.QueryIntegerProperty<ObPeerWatermark>(
    _entities[6].properties[5],
  );

  /// See [ObPeerWatermark.recordKey].
  static final recordKey = obx.QueryStringProperty<ObPeerWatermark>(
    _entities[6].properties[6],
  );
}
